packages:
  - "apps/*"
  - "packages/*"
strictDepBuilds: true
engineStrict: true
verifyDepsBeforeRun: warn
allowBuilds:
  unrs-resolver: true
  sharp: true
  "@nestjs/core": true
  "@scarf/scarf": false
