-- Server-only application records. Run as the database owner after initialization.
-- Intentionally no anon/authenticated policies: all browser traffic uses NestJS.
BEGIN;
REVOKE ALL ON SCHEMA casa_pepe_private FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."incidents" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."incidents" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."webhook_subscriptions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."webhook_subscriptions" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."inbound_emails" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."inbound_emails" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."webhook_deliveries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."webhook_deliveries" FROM PUBLIC, anon, authenticated;
ALTER TABLE "casa_pepe_private"."company_call_sessions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "casa_pepe_private"."company_call_sessions" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."activity_events" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."activity_events" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."tasks" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."plans" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."plans" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."engineer_calls" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."engineer_calls" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."incoming_calls" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."incoming_calls" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."learning_insights" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."learning_insights" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."approvals" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."approvals" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."recovery_actions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."recovery_actions" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."tool_calls" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."tool_calls" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."status_publications" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."status_publications" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."tool_tests" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."tool_tests" FROM PUBLIC, anon, authenticated;
ALTER TABLE "public"."migrations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "public"."migrations" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE casa_pepe_private.incident_call_code_seq FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.migrations_id_seq FROM PUBLIC, anon, authenticated;
COMMIT;
