/** Provider metadata is injected by the integration, never generated by the voice model. */
export interface CallInitiationInput {
  readonly conversationId: string
}
export interface CallInitiationResult {
  readonly sessionReference: string
}
export interface CompanyPriorityRequest {
  readonly kind: "priority-request"
  readonly customerName: string
  readonly requestedPriority: "first"
  readonly reason?: string
}
export interface CallOutcomeInput {
  readonly schemaVersion: 1
  readonly sessionReference: string
  readonly outcome: CompanyPriorityRequest
}
export interface CallOutcomeReceipt {
  readonly accepted: true
  readonly outcomeIdentifier: string
  readonly status: "received"
}
export interface CompanyCallEvidence {
  readonly identifier: string
  readonly runIdentifier: string
  readonly provider: "happyrobot"
  readonly receivedAt: string
  readonly outcome: CompanyPriorityRequest
  readonly customerIdentifier: string | null
  readonly serviceIdentifiers: string[]
  readonly resolution: "matched" | "needs-clarification"
}
