import type { DashboardSnapshot } from "@/lib/dashboard-types";

const INITIAL_SNAPSHOT: DashboardSnapshot = {
  incident: {
    severity: "critical",
    title: "Impacto de meteorito en Madrid",
    description:
      "Nuestro centro de datos principal en Madrid se encuentra fuera de servicio. Múltiples empresas han perdido la conexión. El agente IA está ejecutando el plan de recuperación.",
    localTime: "10:17",
    elapsedLabel: "Hace 7 min",
    impactSiteId: "madrid",
  },
  global: {
    onlinePercent: 42,
    active: 18,
    degraded: 4,
    down: 6,
    companiesOnNetwork: 28,
  },
  impact: {
    companiesOffline: 6,
    companiesTotal: 28,
    usersOffline: 12480,
    companiesDeltaPercent: 100,
    usersDeltaPercent: 100,
  },
  sites: [
    {
      id: "madrid",
      name: "Madrid",
      role: "Centro de datos principal",
      lat: 40.4168,
      lng: -3.7038,
      status: "down",
    },
    {
      id: "barcelona",
      name: "Barcelona",
      lat: 41.3874,
      lng: 2.1686,
      status: "up",
    },
    {
      id: "valencia",
      name: "Valencia",
      lat: 39.4699,
      lng: -0.3763,
      status: "up",
    },
    {
      id: "sevilla",
      name: "Sevilla",
      lat: 37.3891,
      lng: -5.9845,
      status: "up",
    },
    {
      id: "malaga",
      name: "Málaga",
      lat: 36.7213,
      lng: -4.4214,
      status: "up",
    },
    {
      id: "bilbao",
      name: "Bilbao",
      lat: 43.263,
      lng: -2.935,
      status: "up",
    },
    {
      id: "a_coruna",
      name: "A Coruña",
      lat: 43.3623,
      lng: -8.4115,
      status: "up",
    },
    {
      id: "zaragoza",
      name: "Zaragoza",
      lat: 41.6488,
      lng: -0.8891,
      status: "up",
    },
    {
      id: "canarias",
      name: "Islas Canarias",
      lat: 28.2916,
      lng: -16.6291,
      status: "up",
      inset: "canarias",
    },
  ],
  links: [
    { id: "madrid-barcelona", from: "madrid", to: "barcelona" },
    { id: "madrid-valencia", from: "madrid", to: "valencia" },
    { id: "madrid-sevilla", from: "madrid", to: "sevilla" },
    { id: "madrid-malaga", from: "madrid", to: "malaga" },
    { id: "madrid-bilbao", from: "madrid", to: "bilbao" },
    { id: "madrid-a_coruna", from: "madrid", to: "a_coruna" },
    { id: "madrid-zaragoza", from: "madrid", to: "zaragoza" },
  ],
  companies: [
    {
      id: "iberdrola",
      name: "Iberdrola",
      shortName: "Iberdrola",
      sector: "Energía",
      users: 4230,
      status: "down",
      action: "migrating",
      migrationProgress: 100,
      accent: "#00a650",
    },
    {
      id: "santander",
      name: "Santander",
      shortName: "Santander",
      sector: "Banca",
      users: 3120,
      status: "down",
      action: "migrating",
      migrationProgress: 100,
      accent: "#ec0000",
    },
    {
      id: "inditex",
      name: "Inditex",
      shortName: "Inditex",
      sector: "Retail",
      users: 2980,
      status: "down",
      action: "migrating",
      migrationProgress: 100,
      accent: "#1a1a1a",
    },
    {
      id: "telefonica",
      name: "Telefónica",
      shortName: "Telefónica",
      sector: "Telecomunicaciones",
      users: 1450,
      status: "degraded",
      action: "queued",
      migrationProgress: 45,
      etaMinutes: 12,
      accent: "#0066ff",
    },
    {
      id: "repsol",
      name: "Repsol",
      shortName: "Repsol",
      sector: "Energía",
      users: 890,
      status: "degraded",
      action: "queued",
      migrationProgress: 28,
      etaMinutes: 18,
      accent: "#ff8200",
    },
    {
      id: "iag",
      name: "IAG (Iberia)",
      shortName: "IAG",
      sector: "Transporte",
      users: 810,
      status: "degraded",
      action: "queued",
      migrationProgress: 0,
      accent: "#d70428",
    },
  ],
  agent: {
    online: true,
    statusLabel: "Resolviendo incidente",
    progressLabel: "Ejecutando plan",
    completed: 3,
    total: 5,
    quote:
      "Centro de datos de Madrid fuera de servicio. Iniciando migración de cargas de trabajo a Barcelona y Valencia. Priorizando empresas críticas.",
    steps: [
      {
        id: "detect",
        label: "Impacto detectado",
        status: "done",
        time: "10:17",
      },
      {
        id: "analyze",
        label: "Análisis de afectación",
        status: "done",
        time: "10:18",
      },
      {
        id: "plan",
        label: "Plan de recuperación generado",
        status: "done",
        time: "10:19",
      },
      {
        id: "migrate",
        label: "Migrando datos de empresas prioritarias",
        status: "running",
      },
      {
        id: "restore",
        label: "Restaurando conexiones",
        status: "pending",
      },
      {
        id: "operational",
        label: "Todos los servicios operativos",
        status: "pending",
      },
    ],
  },
  camera: {
    title: "Cámara en directo – Madrid DC",
    timestamp: "10:17:03",
  },
  migrationOverallPercent: 50,
  infrastructure: [
    { id: "madrid", name: "Madrid (Principal)", status: "down", capacity: 0 },
    {
      id: "barcelona",
      name: "Barcelona (Secundario)",
      status: "up",
      capacity: 87,
    },
    {
      id: "valencia",
      name: "Valencia (Secundario)",
      status: "up",
      capacity: 72,
    },
    { id: "sevilla", name: "Sevilla", status: "up", capacity: 100 },
    { id: "bilbao", name: "Bilbao", status: "up", capacity: 100 },
    { id: "a_coruna", name: "A Coruña", status: "up", capacity: 100 },
    { id: "malaga", name: "Málaga", status: "up", capacity: 100 },
    { id: "canarias", name: "Islas Canarias", status: "up", capacity: 100 },
  ],
};

export function createInitialSnapshot(): DashboardSnapshot {
  return structuredClone(INITIAL_SNAPSHOT);
}
