import type { DashboardSnapshot } from "@/lib/dashboard-types";

const INITIAL_SNAPSHOT: DashboardSnapshot = {
  incident: {
    severity: "critical",
    localTime: "10:17",
    elapsedMinutes: 7,
    impactSiteId: "madrid",
  },
  global: {
    onlinePercent: 42,
    active: 18,
    degraded: 4,
    down: 6,
    companiesOnNetwork: 28,
  },
  impact: {
    companiesOffline: 6,
    companiesTotal: 28,
    usersOffline: 12480,
    companiesDeltaPercent: 100,
    usersDeltaPercent: 100,
  },
  sites: [
    {
      id: "madrid",
      lat: 40.4168,
      lng: -3.7038,
      status: "down",
      role: "primary",
    },
    { id: "barcelona", lat: 41.3874, lng: 2.1686, status: "up" },
    { id: "valencia", lat: 39.4699, lng: -0.3763, status: "up" },
    { id: "sevilla", lat: 37.3891, lng: -5.9845, status: "up" },
    { id: "malaga", lat: 36.7213, lng: -4.4214, status: "up" },
    { id: "bilbao", lat: 43.263, lng: -2.935, status: "up" },
    { id: "a_coruna", lat: 43.3623, lng: -8.4115, status: "up" },
    { id: "zaragoza", lat: 41.6488, lng: -0.8891, status: "up" },
    {
      id: "canarias",
      lat: 28.2916,
      lng: -16.6291,
      status: "up",
      inset: "canarias",
    },
  ],
  links: [
    { id: "madrid-barcelona", from: "madrid", to: "barcelona" },
    { id: "madrid-valencia", from: "madrid", to: "valencia" },
    { id: "madrid-sevilla", from: "madrid", to: "sevilla" },
    { id: "madrid-malaga", from: "madrid", to: "malaga" },
    { id: "madrid-bilbao", from: "madrid", to: "bilbao" },
    { id: "madrid-a_coruna", from: "madrid", to: "a_coruna" },
    { id: "madrid-zaragoza", from: "madrid", to: "zaragoza" },
  ],
  companies: [
    {
      id: "iberdrola",
      name: "Iberdrola",
      shortName: "Iberdrola",
      sector: "energy",
      users: 4230,
      status: "degraded",
      action: "migrating",
      migrationProgress: 62,
      etaMinutes: 8,
      accent: "#00a650",
    },
    {
      id: "santander",
      name: "Santander",
      shortName: "Santander",
      sector: "banking",
      users: 3120,
      status: "degraded",
      action: "migrating",
      migrationProgress: 48,
      etaMinutes: 11,
      accent: "#ec0000",
    },
    {
      id: "telefonica",
      name: "Telefónica",
      shortName: "Telefónica",
      sector: "telecom",
      users: 2980,
      status: "degraded",
      action: "migrating",
      migrationProgress: 41,
      etaMinutes: 14,
      accent: "#0066ff",
    },
    {
      id: "repsol",
      name: "Repsol",
      shortName: "Repsol",
      sector: "energy",
      users: 890,
      status: "down",
      action: "queued",
      migrationProgress: 0,
      accent: "#ff8200",
    },
    {
      id: "inditex",
      name: "Inditex",
      shortName: "Inditex",
      sector: "retail",
      users: 810,
      status: "down",
      action: "queued",
      migrationProgress: 0,
      accent: "#1a1a1a",
    },
    {
      id: "iag",
      name: "IAG (Iberia)",
      shortName: "IAG",
      sector: "transport",
      users: 450,
      status: "degraded",
      action: "queued",
      migrationProgress: 0,
      accent: "#d70428",
    },
  ],
  agent: {
    online: true,
    completed: 2,
    total: 6,
    currentReasoningKey: "agent.reasoning.current",
    phases: [
      {
        id: "analyze",
        status: "done",
        time: "10:17",
        tools: [
          {
            id: "tool-logs",
            name: "get_incident_logs",
            status: "done",
            summaryKey: "agent.tool.logs.summary",
            detailKey: "agent.tool.logs.detail",
            time: "10:17",
          },
          {
            id: "tool-services",
            name: "query_affected_services",
            status: "done",
            summaryKey: "agent.tool.services.summary",
            detailKey: "agent.tool.services.detail",
            time: "10:18",
          },
          {
            id: "tool-deps",
            name: "analyze_dependencies",
            status: "done",
            summaryKey: "agent.tool.deps.summary",
            detailKey: "agent.tool.deps.detail",
            time: "10:18",
          },
        ],
      },
      {
        id: "plan",
        status: "done",
        time: "10:18",
        tools: [
          {
            id: "tool-plan",
            name: "create_recovery_plan",
            status: "done",
            summaryKey: "agent.tool.plan.summary",
            detailKey: "agent.tool.plan.detail",
            time: "10:18",
          },
        ],
      },
      {
        id: "launch_subagents",
        status: "running",
        time: "10:19",
        subagents: [
          {
            id: "sub-iberdrola",
            name: "Iberdrola",
            companyId: "iberdrola",
            status: "running",
            headlineKey: "agent.subagent.iberdrola.headline",
            reasoningKey: "agent.subagent.iberdrola.reasoning",
            tools: [
              {
                id: "sub-iberdrola-volumes",
                name: "replicate_volumes",
                status: "done",
                summaryKey: "agent.subagent.iberdrola.volumes.summary",
                detailKey: "agent.subagent.iberdrola.volumes.detail",
                time: "10:19",
              },
              {
                id: "sub-iberdrola-sync",
                name: "sync_services",
                status: "running",
                summaryKey: "agent.subagent.iberdrola.sync.summary",
                detailKey: "agent.subagent.iberdrola.sync.detail",
              },
            ],
          },
          {
            id: "sub-santander",
            name: "Santander",
            companyId: "santander",
            status: "running",
            headlineKey: "agent.subagent.santander.headline",
            reasoningKey: "agent.subagent.santander.reasoning",
            tools: [
              {
                id: "sub-santander-db",
                name: "migrate_databases",
                status: "running",
                summaryKey: "agent.subagent.santander.db.summary",
                detailKey: "agent.subagent.santander.db.detail",
              },
            ],
          },
          {
            id: "sub-telefonica",
            name: "Telefónica",
            companyId: "telefonica",
            status: "running",
            headlineKey: "agent.subagent.telefonica.headline",
            reasoningKey: "agent.subagent.telefonica.reasoning",
            tools: [
              {
                id: "sub-telefonica-net",
                name: "replicate_network",
                status: "running",
                summaryKey: "agent.subagent.telefonica.net.summary",
                detailKey: "agent.subagent.telefonica.net.detail",
              },
            ],
          },
        ],
      },
      { id: "restore", status: "pending" },
      { id: "validate", status: "pending" },
      { id: "close", status: "pending" },
    ],
    activity: [
      {
        id: "act-reasoning",
        type: "reasoning",
        textKey: "agent.reasoning.current",
        time: "10:17",
      },
      { id: "act-analyze", type: "phase", phaseId: "analyze" },
      { id: "act-plan", type: "phase", phaseId: "plan" },
      { id: "act-launch", type: "phase", phaseId: "launch_subagents" },
      { id: "act-restore", type: "phase", phaseId: "restore" },
      { id: "act-validate", type: "phase", phaseId: "validate" },
      { id: "act-close", type: "phase", phaseId: "close" },
    ],
  },
  camera: {
    timestamp: "10:17:03",
  },
  migrationOverallPercent: 50,
  infrastructure: [
    { id: "madrid", status: "down", capacity: 0 },
    { id: "barcelona", status: "up", capacity: 87 },
    { id: "valencia", status: "up", capacity: 72 },
    { id: "sevilla", status: "up", capacity: 100 },
    { id: "bilbao", status: "up", capacity: 100 },
    { id: "malaga", status: "up", capacity: 100 },
  ],
};

export function createInitialSnapshot(): DashboardSnapshot {
  return structuredClone(INITIAL_SNAPSHOT);
}
